server:
    port: 8080
spring:
    application:
        name: foodproduct
    datasource:
        password: P@ssword*123
        url: jdbc:postgresql://code4fun.xyz:5432/sustanable_project?currentSchema=sustanable
        username: dev
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
        multipart:
            max-file-size: 25MB
            max-request-size: 25MB

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days
